#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'styling, testing and ubilding your project before committing'

# check tsconfig standards
npm run check-types || 
(
    echo 'Failed Type Check. Please make sure all your types are correctyl configured'
    false;
)
# check prettier formatting standards
npm run check-format || 
(
    echo 'Failed formatting check, please check if all your code has been formatted properly and there are no prettier error then try to commit again'
    false;
)
# check eslint formatting standards
npm run check-lint || 
(
    echo 'Filed eslint check, please check for eslint errors and try to commit again'
    false;
)
# check for build errors
echo 'Alright...code looks good and ready to be build...trying to build now'

npm run build || 
(
    echo 'Your build has failed, view the errors above to see why'
    false;
)
# if build is success 
echo 'Code looks good..Committing this now....'