#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'styling, testing and ubilding your project before committing'

# check tsconfig standards
npm run check-types || 
(
    echo 'Failed Type Check. Please make sure all your types are correctyl configured'
    false;
)
# check prettier formatting standards
npm run check-format || 
(
    echo 'Failed formatting check, please check if all your code has been formatted properly and there are no prettier error then try to commit again'
    false;
)
# check eslint formatting standards
npm run check-lint || 
(
    echo 'Filed eslint check, please check for eslint errors and try to commit again'
    false;
)

echo 'Code looks good..I have committed your code and it is ready to be pushed'